// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/invite/[token]" | "/match/[token]" | "/tournament/[slug]" | "/tournament/[slug]/bracket" | "/tournament/[slug]/matches/[matchId]" | "/tournament/[slug]/standings"
type AppRouteHandlerRoutes = "/api/admin/tournament/bootstrap" | "/api/matches/[token]/scorecard" | "/api/public/tournament/[slug]/bracket" | "/api/public/tournament/[slug]/standings"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/admin/tournament/bootstrap": {}
  "/api/matches/[token]/scorecard": { "token": string; }
  "/api/public/tournament/[slug]/bracket": { "slug": string; }
  "/api/public/tournament/[slug]/standings": { "slug": string; }
  "/invite/[token]": { "token": string; }
  "/match/[token]": { "token": string; }
  "/tournament/[slug]": { "slug": string; }
  "/tournament/[slug]/bracket": { "slug": string; }
  "/tournament/[slug]/matches/[matchId]": { "slug": string; "matchId": string; }
  "/tournament/[slug]/standings": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
